# -*- coding: utf-8 -*-
"""Adversarial test Gen2 — freshly generated bypass samples, no overlap with 36 static cases"""

import sys
sys.path.insert(0, ".")

from privacy_engine import filter_text, scan_text

fresh_cases = [
    # ── Zero-width character insertion ──
    "Server address is 192\u200b.168\u200b.1\u200b.1 — can you ping it?",
    "token=sk\u200b-proj\u200b-abc123def456 — has this key expired?",

    # ── Homoglyph attack (Cyrillic а/е/о replacing Latin a/e/o) ──
    "ssh admin@192.168.1.1 password is s\u0435cr\u0435t_p\u0430ss",

    # ── URL-encoded sensitive data ──
    "The request params have redirect_uri=https%3A%2F%2Fadmin%3Apass123%4010.0.0.1%3A8080",
    "I just saw a connection string: mysql%3A%2F%2Froot%3Ahunter2%40192.168.1.100%3A3306%2Fprod",

    # ── Markdown code block with embedded sensitive info ──
    "```yaml\nproduction:\n  host: 203.0.113.42\n  token: ghp_xJ3kL9mN2pQ5rS8tV1wY4zA7bC0dE3fG6h\n```",

    # ── Multi-line assignment with sensitive values ──
    "DATABASE_URL = (\n"
    "    'postgresql://prod_admin:S3cur3!Pass@db-primary.internal.io:5432/main'\n"
    ")",

    # ── Environment variable reference style ──
    "Set ${AWS_ACCESS_KEY_ID} to AKIAIOSFODNN7EXAMPLE and use ${AWS_SECRET_ACCESS_KEY} to sign",

    # ── HTML entities obfuscation ──
    "Registration email is admin&#64;internal&#46;corp&#46;com but not receiving verification codes",

    # ── JSON escape strings with sensitive data ──
    '{"error": "connection \\"mysql://user:p@ssw0rd@10.20.30.40:3306/db\\" timed out"}',

    # ── IPv4 dotted-decimal with leading zeros ──
    "The firewall rule has 192.168.001.001 — should this inbound policy be deleted?",

    # ── Keyboard layout typo (qwerty→dvorak or common slip) ──
    "vi ~/.ssh/authorized_keys added ssh-rsa AAAAB3NzaC1yc2E... — whose public key is this?",

    # ── Commented-out sensitive config ──
    "// const API_SECRET = 'sk-live-9a8b7c6d5e4f3a2b1c0d9e8f'; // deprecated, pending removal",

    # ── Bash heredoc with credentials ──
    "cat <<EOF > .env\nDB_PASS=Pr0ducti0n#2024!\nREDIS_AUTH=redis-secret-token-here\nEOF",

    # ── Python f-string embedded ──
    "conn = f'mysql://{os.environ[\"DB_USER\"]}:{os.environ[\"DB_PASS\"]}@{os.environ[\"DB_HOST\"]}'",

    # ── Log format with sensitive data ──
    "[2024-06-06 10:23:45] ERROR connection refused user=admin pass=CorrectHorseBatteryStaple host=db-master.prod.internal",

    # ── Phone number in mixed digit/word form ──
    "Emergency contact: one-three-nine-one-two-three-four-five-six-seven-eight or directly dial 138-1234-5678-910",

    # ── Credit card with BIN annotation ──
    "BIN is 4532 01, followed by 11 digits 51123456789 making the full card 45320151123456789",

    # ── AES key in natural language ──
    "I saved the encryption key as a file: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",

    # ── Docker run command with credentials ──
    "docker run -e MYSQL_ROOT_PASSWORD=my-secret-pw -e API_KEY=sk-ant-api03-xxxxx -p 3306:3306 mysql:8",

    # ── K8s secret in plaintext ──
    "apiVersion: v1\nkind: Secret\nmetadata:\n  name: db-credentials\ndata:\n  username: YWRtaW4=\n  password: cGFzc3dvcmQxMjM=",

    # ── Reverse obfuscation — safe words inserted in sensitive patterns ──
    "Temp IP is 192.example.168.com.1.1 — this won't trigger firewall alerts like this, right?",

    # ── ROT13 encoded ──
    "The key is fx-fgernz-ncv-xrl-ebg13-rapbqrq — remember to ROT13 decode before using",

    # ── Base58 encoded (Bitcoin-address-like) ──
    "Test wallet address 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa — has some test coins",

    # ── ID card read aloud in Chinese digit words ──
    "ID card number read aloud: one-one-zero-one-zero-one-one-nine-nine-zero-zero-one-zero-one-one-two-three-four",

    # ── Password in SQL INSERT statement ──
    "INSERT INTO users (email, password_hash) VALUES ('admin@corp.com', '5f4dcc3b5aa765d61d8327deb882cf99')",

    # ── Terraform variable with credential ──
    'variable "db_password" { default = "T3rr4f0rm!S3cur3" }',

    # ── Port number hidden in URL path as disguise ──
    "Visit http://internal-api/connect?target=db-primary&port=5432&user=readonly&pass=guest2024",

    # ── Cron expression with sensitive path ──
    "0 2 * * * /usr/bin/pg_dump -h db.internal -U backup -w -f /backup/daily.sql # password in ~/.pgpass",

    # ── Mixed fullwidth/halfwidth + zero-width ──
    "key=sk-\u200b\uff50\uff52\uff4f\uff4a\u200b-\uff41\uff42\uff43\uff11\uff12\uff13\uff44\uff45\uff46\uff14\uff15\uff16 — can this bypass log filtering?",  # fullwidth: ｐｒｏｊ-ａｂｃ１２３ｄｅｆ４５６
]

print("=" * 70)
print("LLM Privacy Guard — Gen2 Fresh Adversarial Test")
print("=" * 70)
print()

def _safe(s, n=100):
    return s[:n].encode("gbk", errors="replace").decode("gbk")

caught = 0
leaked = 0
leaks = []

for i, case in enumerate(fresh_cases, 1):
    matches = scan_text(case)
    filtered = filter_text(case)

    if matches:
        caught += 1
        types = ", ".join(m["type"] for m in matches)
        print(f"[OK #{i}] Caught ({types})")
        print(f"  Raw     : {_safe(case)}...")
        print(f"  Filtered: {_safe(filtered)}...")
    else:
        leaked += 1
        leaks.append((i, case))
        print(f"[!! #{i}] LEAKED!")
        print(f"  Raw: {_safe(case, 120)}...")
    print()

print("=" * 70)
print(f"Result: {caught} caught / {leaked} leaked / {len(fresh_cases)} total")
if leaked:
    print(f"Leak rate: {leaked / len(fresh_cases) * 100:.1f}%")
    print()
    print("--- Leaked Cases ---")
    for idx, text in leaks:
        print(f"  #{idx}: {_safe(text, 150)}")
print("=" * 70)
